#ifndef ASSETS_H
#define ASSETS_H

#define SOUND_LOOP ((char*)"_aud_loop")
#define SOUND_STEP ((char*)"_aud_step")
#define SOUND_MOD ((char*)"_aud_mod")
#define SOUND_ENTER ((char*)"_aud_enter")
#define SOUND_RANK_S ((char*)"_aud_rank-s")
#define SOUND_RANK_A ((char*)"_aud_rank-a")
#define SOUND_RANK_B ((char*)"_aud_rank-b")
#define SOUND_RANK_C ((char*)"_aud_rank-c")
#define SOUND_RANK_D ((char*)"_aud_rank-d")
#define SOUND_RANK_F ((char*)"_aud_rank-f")
#define SOUND_STAGE_BREAK ((char*)"_aud_break")
#define SOUND_CALIBRATE ((char*)"_aud_calibrate")
#define BG_CONTROLS_TILES ((char*)"_img_controls.img.bin")
#define BG_CONTROLS_PALETTE ((char*)"_img_controls.pal.bin")
#define BG_CONTROLS_MAP ((char*)"_img_controls.map.bin")
#define BG_START_TILES ((char*)"_img_start.img.bin")
#define BG_START_PALETTE ((char*)"_img_start.pal.bin")
#define BG_START_MAP ((char*)"_img_start.map.bin")
#define BG_WALL_TILES ((char*)"_img_wall.img.bin")
#define BG_WALL_PALETTE ((char*)"_img_wall.pal.bin")
#define BG_WALL_MAP ((char*)"_img_wall.map.bin")
#define BG_LINES_TILES ((char*)"_img_lines.img.bin")
#define BG_LINES_PALETTE ((char*)"_img_lines.pal.bin")
#define BG_LINES_MAP ((char*)"_img_lines.map.bin")
#define BG_TALK_TILES ((char*)"_img_talk.img.bin")
#define BG_TALK_PALETTE ((char*)"_img_talk.pal.bin")
#define BG_TALK_MAP ((char*)"_img_talk.map.bin")
#define BG_GRADE_TILES ((char*)"_img_grade.img.bin")
#define BG_GRADE_PALETTE ((char*)"_img_grade.pal.bin")
#define BG_GRADE_MAP ((char*)"_img_grade.map.bin")
#define BG_GRADE_MULTI_TILES ((char*)"_img_grademulti.img.bin")
#define BG_GRADE_MULTI_PALETTE ((char*)"_img_grademulti.pal.bin")
#define BG_GRADE_MULTI_MAP ((char*)"_img_grademulti.map.bin")
#define ROM_ID_FILE ((char*)"_rom_id.u32")
#define ROM_NAME_FILE ((char*)"_rom_name.txt")
#define BONUS_COUNT_FILE ((char*)"_bonus.u32")

#endif  // ASSETS_H
